Using the NumPy functions you learned about on the previous page, create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive).

In [1]:
import numpy as np

# Create a 4x4 ndarray with consecutive even numbers
even_numbers = np.arange(2, 33, 2).reshape(4, 4)

print(even_numbers)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
